select
    "Type"                          as payment_type,
    "Days for shipping (real)"      as days_shipping_real,
    "Days for shipment (scheduled)" as days_shipping_scheduled,
    "Benefit per order"             as benefit_per_order,
    "Sales per customer"            as sales_per_customer,
    "Delivery Status"               as delivery_status,
    "Late_delivery_risk"            as late_delivery_risk,
    "Category Id"                   as category_id,
    "Category Name"                 as category_name,
    "Customer Id"                   as customer_id,
    trim("Customer Fname")          as customer_first_name,
    trim("Customer Lname")          as customer_last_name,
    "Customer Segment"              as customer_segment,
    "Customer City"                 as customer_city,
    "Customer Country"              as customer_country,
    "Customer State"                as customer_state,
    "Customer Zipcode"              as customer_zipcode,
    "Department Id"                 as department_id,
    "Department Name"               as department_name,
    "Latitude"                      as customer_latitude,
    "Longitude"                     as customer_longitude,
    "Market"                        as market,
    "Order City"                    as order_city,
    "Order Country"                 as order_country,
    "Order Region"                  as order_region,
    "Order State"                   as order_state,
    "Order Zipcode"                 as order_zipcode,
    "Order Id"                      as order_id,
    "Order Customer Id"             as order_customer_id,
    "Order Status"                  as order_status,
    "order date (DateOrders)"       as order_date_raw,
    "shipping date (DateOrders)"    as shipping_date_raw,
    "Order Item Id"                 as order_item_id,
    "Order Item Cardprod Id"        as order_item_cardprod_id,
    "Order Item Discount"           as order_item_discount,
    "Order Item Discount Rate"      as order_item_discount_rate,
    "Order Item Product Price"      as order_item_product_price,
    "Order Item Profit Ratio"       as order_item_profit_ratio,
    "Order Item Quantity"           as order_item_quantity,
    "Order Item Total"              as order_item_total,
    "Sales"                         as sales,
    "Order Profit Per Order"        as order_profit_per_order,
    "Product Card Id"               as product_card_id,
    "Product Category Id"           as product_category_id,
    "Product Name"                  as product_name,
    "Product Price"                 as product_price,
    "Product Status"                as product_status,
    "Shipping Mode"                 as shipping_mode
from {{ source('raw', 'supply_chain_raw') }}